### ISSUE TITLE
Saving metrics property doens't work

### ISSUE THREAD

**Issue by rBoncorps** [SOM-Research/collaboro#17]
Due to the new handling of the metrics configuration file, the saving method is not working anymore. Indeed, the metrics configuration file is handled with an input stream given by the recommender servlet (and not an file path). So it's not possible to open an output stream to save the changes in the metrics configuration file.
This could be fixed by giving the file path to the metricConfigurationHandler.

**Comment by jlcanovas** [comment]
Fixed in 7cc46862ece3597c671f4de9d5e26608611dac31
